"""empty message

Revision ID: 89e640219cb2
Revises: ea2e4c48287b
Create Date: 2020-01-17 19:56:19.108318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e640219cb2'
down_revision = 'ea2e4c48287b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer', sa.Column('is_verified', sa.Integer(), nullable=True))
    op.add_column('seller', sa.Column('is_verified', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'is_verified')
    op.drop_column('buyer', 'is_verified')
    # ### end Alembic commands ###
